### ISSUE TITLE
The code cannot run successfully

### ISSUE THREAD

**Issue by smiles724** [MinkaiXu/ConfVAE-ICML21#1]
Hi, thanks for sharing the code.

However, when I reran the code without any modification. I came across the following issue, can you please give any guidance or help to solve it? 
![image](https://user-images.githubusercontent.com/39299863/132084210-5aeda603-c3e5-43c1-bbbd-ba5186d8649b.png)

**Comment by MinkaiXu** [comment]
Hi, thx for your interest. It seems you have fixed it and closed the issue? I think the error is about the version of torchdiffeq, and maybe you can fix it by switching it to our used version.

**Comment by smiles724** [comment]
Yeah, I found it was due to the version of torchdiffeq, and fixed it myself!
