### ISSUE TITLE
Generation Procedure during Evalution 

### ISSUE THREAD

**Issue by smiles724** [MinkaiXu/ConfVAE-ICML21#2]
Hi, I notice there are two kinds of generation functions in the eval file. And you used 

`def em_generate_batch(model: EdgeCNF, data, num_samples, embedder=Embed3D(), dg_init_pos=None, em_steps=0):` 

to produce molecular conformations. However, this process is different from what the Imodel is trained when calculating the reconstruction loss. I also notice that you set the em_step to 0. 

Did you actually use this method for the generation? If so, is this more sophisticated approach better than the simple one? Can you provide more details about this method, or perhaps give me some references? 

Great thanks!

**Comment by MinkaiXu** [comment]
Hi!

As hardcoded in the code, the number of EM steps is set as 0. Then this leads to the same sampling method as the training procedure. 
More specifically, as shown in https://github.com/MinkaiXu/ConfVAE-ICML21/blob/d1d7469a67c82fc0e5d0d3bf8ce3572376f15a10/models/edgecnf.py#L264, em_steps=0 will skip the loop here, and the sampling procedure will be the same as how we compute the reconstruction loss.

For performance, I remember I tried to increase the em_steps but the improvement is quite limited, with much more computational cost. So I didn't employ it finally.

Best,
Minkai
