### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Neo-Flash** [MinkaiXu/ConfVAE-ICML21#3]
Hi！thank u for sharing ur work
How long does this default model take to train? 
Can you provide a pre-trained model?

**Comment by MinkaiXu** [comment]
Hi Flash,

Thank you for your interest!

You can ignore the max_epoch in the configuration, which is just used for training the model for an arbitrarily long time.
I remember ~48h is already enough to get a good model. You could run ~48h and test whether you can roughly reproduce the results. Ping me if there is still some issue.

For the pretrained model, I just looked through my storage and it seems the huge checkpoints have been automatically pruged by MILA cluster policy (https://docs.computecanada.ca/wiki/B%C3%A9luga/en#Storage)... Sorry but you know there has been one year for this project...
But I believe you could just run with my default hyperparameters and roughly reproduce the results. Maybe you need a different KL weight for different datasets (https://github.com/MinkaiXu/ConfVAE-ICML21/blob/main/train_vae.py#L31-L32), but I remember this actually also doesn't matter a lot.

Ping me if you still have other problems :)

Best
Minkai

**Comment by Neo-Flash** [comment]
Got it, thank you! I will continue to train, it has just been 12 hours

祝您新年吉祥，实验顺利！✨
